spring.application.name=url-cutter-api

server.port=8081

security.rsa.key-size=3072

# Chave secreta JWT

jwt.secret=jW5vunRAcuQc569wdaft0tTsdhSQcvZ89KNbJ5bnFVc=

# Url base da api

app.base-url=http://localhost:8081/r/

# EMAIL CONFIG

resend.api-key2=re_YiibfYqM_PfARh6djgJrPMcnBWSiHemDg

resend.api-key=re_d96yRyDS_6wRNuoCfKKDkxkKupS4G43FU

# DATABASE

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/url-cutter
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres2408